### ISSUE TITLE
Conflict between touchégg gestures and those of default gnome in wayland on non-gtk windows. 

### ISSUE THREAD

**Issue by DuttaAB-dev** [pop-os/gnome-shell-extension-pop-cosmic#59] opened 2021-05-28 08:23 UTC

**Comment by leviport** [comment] 2021-07-20 18:23
This is a duplicate of https://github.com/pop-os/cosmic/issues/110. Even though this one was filed first, that issue seems to have more information, so I'm going to close this one.

**Closed as completed by leviport** 2021-07-20 18:23 UTC
