### ISSUE TITLE
Wrong size of the application menu

### ISSUE THREAD

**Issue by it2000-the-original** [pop-os/gnome-shell-extension-pop-cosmic#334] opened 2022-04-26 19:39 UTC
There is a problem with the application menu, in some others resolutions of the screen the applications menu is proportionate, but in the resolution 1366x768 (16:9) it is not and does not enter the screen, this is a screenshot:
![Screenshot from 2022-04-26 21-23-23](https://user-images.githubusercontent.com/93731405/165378878-c1831566-4342-48b8-9e9a-58ea8b1e36fe.png)

**Comment by leviport** [comment] 2022-04-26 19:55
Duplicate of https://github.com/pop-os/cosmic/issues/314

**Closed as completed** 2022-04-26 19:55 UTC
