### ISSUE TITLE
Adjust 4-finger swipe up and down to accomodate natural scrolling

### ISSUE THREAD

**Issue by chuck-r** [pop-os/gnome-shell-extension-pop-cosmic#248] opened 2021-11-24 22:45 UTC
When enabling the Natural Scrolling option, the four-finger swipe up and down gestures don't change.

Expected behavior:
* Default scrolling: Swipe down goes to next desktop, scrolling the screen upward in the process
* Natural scrolling: Swipe down goes the previous desktop, scrolling the screen downward in the process

Actual behavior:
Regardless of natural scrolling configuration, swipe down always goes to the next desktop (as in, it scrolls the screen upward to go to a desktop sitting below the current desktop). This is a little confusing with natural scrolling enabled as it seems to be backward compared to everything else. COSMIC should check/watch the value of `org.gnome.desktop.peripherals.touchpad.natural-scroll` and reverse the actions of GESTURE_UP and GESTURE_DOWN according to the setting.

**Comment by leviport** [comment] 2021-11-29 15:37
Thank you for the report! I'm closing it as a duplicate of https://github.com/pop-os/cosmic/issues/110. In that issue, I also posted a workaround which you can use to fix it until a fix becomes available.

**Closed as completed by leviport** 2021-11-29 15:37 UTC
