### ISSUE TITLE
Launcher shortcut works only with English keyboard layout.

### ISSUE THREAD

**Issue by Avendattor** [pop-os/gnome-shell-extension-pop-cosmic#108] opened 2021-07-01 08:34 UTC
I have two language keyboard layout. All shortcuts works perfect with all layouts (App View, Workspaces view, all other), but "Launcher" works only with English layout. For example, when I am on RU layout, i have to switch to EN, otherwise Launcher shortcut won't work. 

Pressing Super + '/' triggers only input character that belongs to this key on RU keyboard. 

List of my layouts:
![Screenshot from 2021-07-01 11-31-11](https://user-images.githubusercontent.com/47778996/124092837-f3163800-da5f-11eb-99e2-25efd90250ed.png)

**Comment by ids1024** [comment] 2021-07-01 19:49
Duplicate of https://github.com/pop-os/shell/issues/531, which is also with the RU layout.

As described there, this is due to behavior in Gnome's keybinding handling that can probably be considered a bug. As a workaround, you can use "Customize Shortcuts" to bind it to something else.

Upstream Gnome issue I opened for this: https://gitlab.gnome.org/GNOME/mutter/-/issues/1417

**Closed as completed by ids1024** 2021-07-01 19:49 UTC
