### ISSUE TITLE
Workspaces view does not search apps (switch to App view on typing)

### ISSUE THREAD

**Issue by Avendattor** [pop-os/gnome-shell-extension-pop-cosmic#85] opened 2021-06-22 06:14 UTC
All the time i used this wonderful feature:

1. Tap command button (or open Workspaces view)
2. Start typing app name
3. (View switches to Application view)
4. Select an app from search results and press Enter (or click)

Couple of weeks ago i noticed that auto switch to App view by typing was disabled (2-4 points dont work). So i have to open Application view instead of Workspaces view for search apps by typing.

Opening Application view is useless for me (and not easy because of shortcuts), i never used it before. And i used to launch apps quickly by typing name.

Please return auto-switch to App view (and app search on typing) from Workspaces view or add a optional switch or something.

Thanks!

**Comment by blakeridgway** [comment] 2021-06-22 08:30
Please review [shell #1018](https://github.com/pop-os/shell/pull/1018)  this was just merged for fixing this issue.

**Comment by munoztd0** [comment] 2021-06-24 12:10
same here!

**Comment by jmbuhr** [comment] 2021-06-27 20:36
Related / same issues: https://github.com/pop-os/cosmic/pull/70, https://github.com/pop-os/shell/issues/995, but should be useful data to the devs that more people are struggling with this.

**Comment by jmbuhr** [comment] 2021-06-27 20:41
And this is probably a weird thing to throw in here, but might nonetheless provide valuable feedback from people that don't necessarily open a GitHub issue: this linux reviewer and the people in his comment section on YouTube tend to agree: https://www.youtube.com/watch?v=y-uUv1jkKOQ

**Comment by DuttaAB-dev** [comment] 2021-06-28 23:01
Wouldn't it be better to rather open up a discussion for this issue? A lot of people for sure are gonna come up there. And that would also rather keep the issues section clean, reserved to real bugs and fixes.

**Comment by Avendattor** [comment] 2021-06-29 07:12
[Discussion](https://github.com/pop-os/cosmic/discussions/95) created.

**Comment by Lestibournes** [comment] 2021-12-17 09:44
> Wouldn't it be better to rather open up a discussion for this issue? A lot of people for sure are gonna come up there. And that would also rather keep the issues section clean, reserved to real bugs and fixes.

This is a bug: a design bug that causes a regression compared to previous versions.

**Comment by leviport** [comment] 2021-12-17 17:22
>This is a bug: a design bug that causes a regression compared to previous versions.

It was a design change. Those who disagree with the change should hop into the discussion thread so we can suss it out.

**Comment by PoignardAzur** [comment] 2023-03-14 12:30
> It was a design change. Those who disagree with the change should hop into the discussion thread so we can suss it out.

> There is already a discussion thread for this: https://github.com/pop-os/cosmic/discussions/95

This all feels increasingly user-hostile.

The linked thread can be summarized as:

- Someone makes a long list of reasons the update broke their workflow, with tens of upvotes.
- mmstick replies with a single link to a blog post and no text (which itself feels pretty dismissive).
- Another user explains why that link doesn't address the broken workflow.
- mmstick gives another response that boils down to "your workflow was invalid".
- About 40 more messages complaining that this breaks their workflow, including someone who actually went and did a mockup and toy implementation.
- No further response from mmstick, no acknowledgement from the team.

This is the kind of attitude people have learned to expect from Gnome devs, not from System76. "The change you want is invalid, you're wrong for wanting the old behavior, we know better, don't bother us with it".

And I get that this is an open-source project and we're not entitled to anyone's work or even acknowledgment... but acknowledgment would go a long way here.

Especially since people are actually willing to put in the work! There's a small minority that *really* wants the old workflow, and they'll write the pull requests if you give them the go-ahead. The code changes are really small, so you don't need to worry about increased maintainer burden.

Like, I'm a little baffled by the dismissiveness and almost hostility from PopOS maintainers here. Saying "there's already a thread full of people complaining about this with us responding that their complaints are invalid, you should go to that thread so we can tell you the same thing or just ignore you" is just tone-deaf.

Again, I get that nobody is entitled to PopOS maintainers' time. But this is an issue some users clearly care a lot about and I feel like maintainers should at least acknowledge that, instead of trying to sweep it under the rug.

**Comment by leviport** [comment] 2023-03-14 14:09
You appear to have interpreted our reactions rather uncharitably. I'd prefer to have this discussion in good faith, if you don't mind.

We aren't saying that anyone's workflow or preferences are invalid. We're saying that our design direction may diverge a bit from what some expect. While it's regrettable that we can't please everyone, we still wish to continue with our vision. Also, "don't bother us" doesn't line up with us continuing to have this discussion, over and over again, like I'm doing again now. Your claim that there was no engagement in the discussion is just not true. I've been in there the whole time, and I reply to people who appear interested in the discussion (rather than just venting frustrations).

>Especially since people are actually willing to put in the work!

Respectfully, I believe that is not the case. As Pop QA, it is my job to be intimately familiar with all pull requests made against our repositories. I have not seen one to add an option that combines the workspaces and applications views. If someone wants to open such a PR, we're happy to review it (although we can't guarantee that it will be accepted, of course).

It's also somewhat of a moot point. The Gnome-based COSMIC environment is not going to be receiving very much new development attention. If anything, changes on it will be discouraged, since we need to use it as a reference for the new COSMIC DE while it is being developed. This has been the workflow since 21.04. Two years later, we still only have an occasional user that gets upset enough to accuse us of acting like Gnome devs. It's regrettable that some are upset, but at least it seems like a small minority.

>Like, I'm a little baffled by the dismissiveness and almost hostility from PopOS maintainers here. Saying "there's already a thread full of people complaining about this with us responding that their complaints are invalid, you should go to that thread so we can tell you the same thing or just ignore you" is just tone-deaf.

There is no progress in sight in this matter. There is just a handful of people that want to yell, and it grew tiresome long ago. If someone were to make a pull request that _optionally_ adds the feature you want, with a toggle switch in the extension's options, there would be a lot more engagement and consideration. 

Also, please don't misconstrue my diligence for cleaning up duplicate threads with dismissiveness. I closed #386 because there was discussion already happening in other places. Centralizing discussions is good for productivity, and that was my only motive behind closing your issue.

**Comment by PoignardAzur** [comment] 2023-03-14 15:37
> I'd prefer to have this discussion in good faith, if you don't mind.

Right.

I don't think you've been discussing in bad faith, but I do think the collective attitude of PopOS about this issue has been dismissive. As in, "dismissive" feels like the accurate label for the patterns I've observed.

> There is no progress in sight in this matter. There is just a handful of people that want to yell, and it grew tiresome long ago.

With all due respect, and with all the caveats I mentioned earlier (nobody is entitled to your time, etc), I think you're being very uncharitable here. The people on that thread were overall extremely polite; the one impolite message got "👎" reactions. While a lot of people in that thread were critical, they were also cordial, optimistic, and constructive in their criticisms.

> > Especially since people are actually willing to put in the work!
>
> Respectfully, I believe that is not the case. As Pop QA, it is my job to be intimately familiar with all pull requests made against our repositories.

I was referring to @WatchMkr's [alternative UI mockup](https://github.com/pop-os/shell/issues/1186) and @ArthurVardevanyan's [set of patches](https://github.com/pop-os/cosmic/discussions/95#discussioncomment-1474023). Also, speaking for myself, I *will* work on a PR if maintainer feedback proves encouraging (more on that in a bit).

> I have not seen one to add an option that combines the workspaces and applications views. If someone wants to open such a PR, we're happy to review it (although we can't guarantee that it will be accepted, of course).
>
> It's also somewhat of a moot point. The Gnome-based COSMIC environment is not going to be receiving very much new development attention. If anything, changes on it will be discouraged

I mean, that last paragraph explains the first, doesn't it?

Developers don't write PRs if maintainers signal "we're not interested in this and we'll probably reject any changes you suggest" ahead of time. That was part of why I opened issue #386: to get a feel of the land and see if maintainers would be open to such a PR.

> If someone were to make a pull request that optionally adds the feature you want, with a toggle switch in the extension's options, there would be a lot more engagement and consideration.

This is encouraging to hear!

I wish this had been communicated in the discussion thread, because it wasn't the vibe I got from it at all. I'll look into making a PR soon.

> Also, please don't misconstrue my diligence for cleaning up duplicate threads with dismissiveness. I closed #386 because there was discussion already happening in other places. Centralizing discussions is good for productivity, and that was my only motive behind closing your issue.

Thanks for your response! I know my previous message was harsh, but I really appreciate that you took the time to hash everything out.

**Comment by leviport** [comment] 2023-03-21 14:12
Since it was mentioned in the [mockup issue](https://github.com/pop-os/shell/issues/1186) that this feature is being deferred to COSMIC DE, I'm going to close this issue, but I will leave the [discussion thread](https://github.com/pop-os/cosmic/discussions/95) open for all who wish to continue the discussion. 

Community PRs will be considered and tested, but we probably won't have engineering bandwidth for developing these features ourselves.

**Closed as completed by leviport** 2023-03-21 14:12 UTC
