### ISSUE TITLE
Inputs freeze after mashing Tab/PgUp/PgDn

### ISSUE THREAD

**Issue by 13r0ck** [pop-os/gnome-shell-extension-pop-cosmic#250] opened 2021-11-30 17:47 UTC
After merging #240, it creates this bug.

It is possible to break the Tab/PgUp/PgDn by pressing the the following combination of keys
```
Super+A
PgDn
PgUp
PgUp
PgUp
Tab
PgDn
```
Then PgUp/PgDn/Tab will do nothing. The key presses don't break it every time ~50% of the time.
I think it has to do with over/under indexing the folder values maybe. I also got the issue by pressing PgDn too many times, but that was less reliable.
(Also reproduced [here](https://github.com/pop-os/cosmic/pull/240#issuecomment-972073504))

https://user-images.githubusercontent.com/58987761/142259704-3ac0faed-297d-40f5-8a4b-6126c91ee83a.mp4

**Comment by WatchMkr** [comment] 2022-02-17 03:02
I found this one pretty hard to reproduce. Because we're re-writing the Application Library for COSMIC DE, I think it's safe to close this one and fix other papercuts for 22.04.

**Closed as completed by WatchMkr** 2022-02-17 03:02 UTC
