### ISSUE TITLE
Pop 22.04/Gnome 42 : Applications Library must be manually dismissed.

### ISSUE THREAD

**Issue by XV-02** [pop-os/gnome-shell-extension-pop-cosmic#324] opened 2022-03-29 00:02 UTC
After opening the Application Library, clicking outside the library does not dismiss it, and no other elements on-screen can be interacted with. 

Activating the launcher or workspaces view clears the Application Library. Super-t launches a terminal, and Super-f launches the file viewer. ~However, Super-y _does not_ toggle tiled mode correctly.~ (Strike through:  This is not regressive behaviour.)

**Comment by ids1024** [comment] 2022-03-29 16:35
Hm, clicking outside the app library seems to be working as expected in my 22.04 VM, as do clicking on "Applications", using super+a, opening an app, etc.

**Comment by storyaddict** [comment] 2022-03-30 16:30
I can confirm this issue as well.

Steps to Reproduce:

1. Install 22.04 ISO in GNOME Boxes.
2. Open Applications Menu
3. Click Applications Menu again to close - menu doesn't close.
4. Click Applications Menu on Dock - menu doesn't close.
5. Click outside of Applications Menu - menu doesn't close.
6. Click ESC key. Menu closes.
7. Apply all updates.
8. Test 2-6 again. - no change.

See attached video. Video was recorded before updates, but behavior persisted after updates and a reboot.

Wormhole link to video: https://wormhole.app/1oYaq#AhfpkaYMdeXKawYa_F01Bg

**Comment by ids1024** [comment] 2022-03-30 17:38
Okay, I see this booting the latest debug ISO. I'll see if I can figure out what's going on here.

**Comment by ids1024** [comment] 2022-03-30 19:11
Clicking outside the Launcher seems to also not close it any more. Something must have changed in how Gnome Shell 42 handles mouse events and dialogs.

**Comment by ids1024** [comment] 2022-03-30 19:55
As I understand it, changes to Mutter/Gnome Shell grab handling in https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2045 and related changes is preventing events like `button-press-event` from propagating up.

**Comment by storyaddict** [comment] 2022-04-01 23:47
I can confirm that the freshly downloaded Beta ISO still has this behavior. It was present in the live boot before doing an install.

I chose to encrypt the install and booted to busybox, so haven't had a chance to test again post install or after updates. But I suspect the busybox thing warrants a separate bug report.

**Comment by postnick** [comment] 2022-04-02 02:40
Uploading video with sound to show my example. 

Fully updated per appstore and apt update at 9:30 pm central time on April 1 2022. 


https://user-images.githubusercontent.com/8466253/161362649-3095bb58-5bd7-4070-9c3a-36c4b33e6dba.mp4

**Closed as completed** 2022-04-04 19:37 UTC
