### ISSUE TITLE
Greyed out selected element in launcher window

### ISSUE THREAD

**Issue by kkorus** [pop-os/gnome-shell-extension-pop-cosmic#385] opened 2023-03-04 09:01 UTC
Lately I have reinstalled Pop_os to 22.04 I have a greyed out selected element in launcher window, which I believe it had different colour before. Do you know how to fix it?

![Screenshot from 2023-03-04 09-46-07](https://user-images.githubusercontent.com/2054009/222886880-2beb9bb3-3122-490b-8d50-68d626ab1456.png)

**Comment by leviport** [comment] 2023-03-06 14:28
Duplicate of https://github.com/pop-os/shell/issues/132

**Closed as completed by leviport** 2023-03-06 14:28 UTC
