### ISSUE TITLE
Cosmic applicatins  launcher doesn't adapt to the resolution screen

### ISSUE THREAD

**Issue by ynoalberto** [pop-os/gnome-shell-extension-pop-cosmic#273] opened 2021-12-20 19:33 UTC
The application launcher doesn't adapt in other monitors and display resolution, for example laptops and PC Desktopa

**Comment by leviport** [comment] 2021-12-21 00:46
Could you post a screenshot of the issue you're seeing? If you're referring to the application library, rather than the launcher, then this issue is likely a duplicate of https://github.com/pop-os/cosmic/issues/264

**Comment by ynoalberto** [comment] 2021-12-21 03:26
Yes, I have 1366x768 resolution size on my laptop and the application library doesn't adapt in the display of my laptop, how I could fix it?

![Captura de pantalla de 2021-12-20 23-17-40](https://user-images.githubusercontent.com/67173989/146865730-a5916426-10ba-409e-aa55-46efd902459d.png)

**Comment by ynoalberto** [comment] 2021-12-21 03:45
And I'm use the Pop OS 21.10 Stable Release

**Comment by leviport** [comment] 2021-12-21 15:48
Thanks for the info. Closing as a duplicate of https://github.com/pop-os/cosmic/issues/264

**Closed as completed by leviport** 2021-12-21 15:48 UTC
