### ISSUE TITLE
The mouse cursor is moving when the workspace is exchanged

### ISSUE THREAD

**Issue by danielnd14** [pop-os/gnome-shell-extension-pop-cosmic#387] opened 2023-03-25 14:48 UTC
The mouse cursor is moving to the left top corner from the active window when we exchange the workspace. This bug is a little bit annoying because if you don't know about this behavior you will lose the mouse pointer on a big screen.

You can follow these steps to reproduce this annoying behavior:
open several apps each of them in a separate workspace. Eg, Terminal, Chrome, Libreoffce, Firefox...

Let's say that the terminal is in workspace 1, and you are watching a video on firefox in workspace 4. So if you drag the mouse into the terminal icon on the dock and click, The cosmic/gnome will exchange the workspace for showing the terminal at the same time the cursor of the mouse will be moved to the left top corner of the terminal.

**Comment by Felipe-Abreu** [comment] 2023-03-25 17:50
I also think that this behavior is annoying.

**Comment by nachoregulardude** [comment] 2023-03-26 13:08
I too faced this problem, please fix

**Comment by DFMaia** [comment] 2023-03-26 14:28
I am having the exact same problem.

**Comment by chrystianSweickDev** [comment] 2023-03-26 20:37
Same issue here, too annoying...

**Comment by leviport** [comment] 2023-03-27 13:59
Duplicate of https://github.com/pop-os/shell/issues/1557

This is now a setting, and you can turn it off.

**Closed as completed by leviport** 2023-03-27 13:59 UTC

**Comment by danielnd14** [comment] 2023-03-27 14:53
Okay, I saw the config on https://github.com/pop-os/shell/issues/1557, but `settings/Mouse & touchpad` should be a better place for this config, isn't it?

PS: I looked for this setting everywhere mouse related but never would have thought it would be in gnome extensions


BTW @leviport thanks for the help, I fixed this behavior on my laptop. :)

**Comment by leviport** [comment] 2023-03-27 15:14
Pop Shell is an extension, so all related Pop Shell settings have to be in the extension settings. Deeper integration will happen in COSMIC DE, but for now there are limitations with the way we've created the COSMIC workflow on top of GNOME with extensions.
