### ISSUE TITLE
Session crashes from closing Steam window

### ISSUE THREAD

**Issue by BrickEater** [pop-os/gnome-shell-extension-pop-cosmic#443] opened 2024-11-13 04:43 UTC
Forgive me if this isn't formatted well, I've never submitted an issue before.

My Cosmic-Session is crashing whenever I try to close the Steam window. I have also had it crash from trying to paste something in Neovim.

I'm not great with error messages but I think these are the ones that are related to the issue:

```Nov 12 21:33:35 goblin-cave cosmic-session[104269]: restarted process ' DISPLAY=:1 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=84 cosmic-idle ', now at 12 restarts
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: Failed to spawn scope for cosmic-idle. Creating transient unit failed with org.freedesktop.systemd1.UnitExists: Unit cosmic-idle.scope was already loaded or has a fragment file.
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: thread 'main' panicked at src/main.rs:230:10:
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: called `Result::unwrap()` on an `Err` value: NotPresent
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: process ' DISPLAY=:1 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=84 cosmic-idle ' failed with code 101
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: cosmic-idle exited with error 101
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: draining stdin receiver before restarting process
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: sleeping for 0ms before restarting process cosmic-idle (restart 12)
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: restarted process ' DISPLAY=:1 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=86 cosmic-idle ', now at 13 restarts
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: sending 1 fds
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: Failed to spawn scope for cosmic-idle. Creating transient unit failed with org.freedesktop.systemd1.UnitExists: Unit cosmic-idle.scope was already loaded or has a fragment file.
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: thread 'main' panicked at src/main.rs:230:10:
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: called `Result::unwrap()` on an `Err` value: NotPresent
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: process ' DISPLAY=:1 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=86 cosmic-idle ' failed with code 101
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: cosmic-idle exited with error 101
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: draining stdin receiver before restarting process
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: sleeping for 65536ms before restarting process cosmic-idle (restart 13)
Nov 12 21:33:35 goblin-cave cosmic-session[104269]: sending 1 fds
Nov 12 21:33:39 goblin-cave cosmic-session[104269]: [2024-11-13T04:33:39Z ERROR cosmic_workspaces::backend::wayland::screencopy] Screencopy failed: Value(BufferConstraints)
Nov 12 21:33:39 goblin-cave cosmic-session[104269]: [2024-11-13T04:33:39Z ERROR cosmic_workspaces::backend::wayland::screencopy] Screencopy failed: Value(BufferConstraints)
```

**Comment by leviport** [comment] 2024-11-13 14:07
I believe this is a duplicate of https://github.com/pop-os/cosmic-epoch/issues/1144. 

Also, this repo is not for COSMIC DE. Bugs with COSMIC DE should be reported in https://github.com/pop-os/cosmic-epoch/

**Closed as completed by leviport** 2024-11-13 14:07 UTC

**Comment by BrickEater** [comment] 2024-11-19 01:31
Sorry for the late response. Thanks for pointing me in the right direction
