### ISSUE TITLE
Workspace switcher making room for dock even if disabled.

### ISSUE THREAD

**Issue by bflanagin** [pop-os/gnome-shell-extension-pop-cosmic#174] opened 2021-07-26 18:23 UTC
If the workspace switcher and the dock are on the left side and you turn off the dock in settings (but the extension is still enabled) the switcher makes room for the dock. 

![Screenshot from 2021-07-26 12-14-40](https://user-images.githubusercontent.com/10382037/127038904-2f03494c-94a1-427c-ae1e-8bb143e50b2e.png)

## Version

pop-cosmic:
  `Installed: 0.1.0~1627319375~21.04~d22439e`

## Expected results
Switcher shouldn't make room for the dock.

**Comment by ids1024** [comment] 2021-07-26 18:51
This seems to be a duplicate of https://github.com/pop-os/cosmic/issues/56.

**Comment by jacobgkau** [comment] 2021-07-28 14:28
Duplicate of https://github.com/pop-os/cosmic/issues/56.

**Closed as completed by jacobgkau** 2021-07-28 14:28 UTC
